In [2]:
import pandas as pd

# Try reading with error handling
data_path = r"C:\Users\Lian4ik\Desktop\derm_project\data\merged_cleaned_dataset.csv"

try:
    # Read CSV with error handling (Using 'on_bad_lines' instead of 'error_bad_lines')
    df = pd.read_csv(data_path, on_bad_lines="skip")  # Skips bad lines
    print("‚úÖ CSV loaded successfully!")
except pd.errors.ParserError as e:
    print("‚ùå Error loading CSV:", e)

# Check first few rows
df.head()

‚úÖ CSV loaded successfully!

             image_id  target     sex  age_approx
0  ISIC_0015290_0.JPG       0  female        30.0
1  ISIC_0015291_0.JPG       0  female        35.0
2  ISIC_0015292_0.JPG       0    male        60.0
3  ISIC_0015293_0.JPG       0  female        45.0
4  ISIC_0015294_0.JPG       0  female        30.0

In [4]:
with open(data_path, "r", encoding="utf-8") as file:
    for i, line in enumerate(file):
        print(f"Line {i+1}: {len(line.strip().split(','))} columns")
        if i == 100:  # Check first 5 lines
            break

Line 1: 4 columns
Line 2: 4 columns
Line 3: 4 columns
Line 4: 4 columns
Line 5: 4 columns
Line 6: 4 columns
Line 7: 4 columns
Line 8: 4 columns
Line 9: 4 columns
Line 10: 4 columns
Line 11: 4 columns
Line 12: 4 columns
Line 13: 4 columns
Line 14: 4 columns
Line 15: 4 columns
Line 16: 4 columns
Line 17: 4 columns
Line 18: 4 columns
Line 19: 4 columns
Line 20: 4 columns
Line 21: 4 columns
Line 22: 4 columns
Line 23: 4 columns
Line 24: 4 columns
Line 25: 4 columns
Line 26: 4 columns
Line 27: 4 columns
Line 28: 4 columns
Line 29: 4 columns
Line 30: 4 columns
Line 31: 4 columns
Line 32: 4 columns
Line 33: 4 columns
Line 34: 4 columns
Line 35: 4 columns
Line 36: 4 columns
Line 37: 4 columns
Line 38: 4 columns
Line 39: 4 columns
Line 40: 4 columns
Line 41: 4 columns
Line 42: 4 columns
Line 43: 4 columns
Line 44: 4 columns
Line 45: 4 columns
Line 46: 4 columns
Line 47: 4 columns
Line 48: 4 columns
Line 49: 4 columns
Line 50: 4 columns
Line 51: 4 columns
Line 52: 4 columns
Line 53: 4 columns
Line 54: 4 columns
Line 55: 4 columns
Line 56: 4 columns
Line 57: 4 columns
Line 58: 4 columns
Line 59: 4 columns
Line 60: 4 columns
Line 61: 4 columns
Line 62: 4 columns
Line 63: 4 columns
Line 64: 4 columns
Line 65: 4 columns
Line 66: 4 columns
Line 67: 4 columns
Line 68: 4 columns
Line 69: 4 columns
Line 70: 4 columns
Line 71: 4 columns
Line 72: 4 columns
Line 73: 4 columns
Line 74: 4 columns
Line 75: 4 columns
Line 76: 4 columns
Line 77: 4 columns
Line 78: 4 columns
Line 79: 4 columns
Line 80: 4 columns
Line 81: 4 columns
Line 82: 4 columns
Line 83: 4 columns
Line 84: 4 columns
Line 85: 4 columns
Line 86: 4 columns
Line 87: 4 columns
Line 88: 4 columns
Line 89: 4 columns
Line 90: 4 columns
Line 91: 4 columns
Line 92: 4 columns
Line 93: 4 columns
Line 94: 4 columns
Line 95: 4 columns
Line 96: 4 columns
Line 97: 4 columns
Line 98: 4 columns
Line 99: 4 columns
Line 100: 4 columns
Line 101: 4 columns

In [5]:


# Get expected number of columns (from header)
with open(data_path, "r", encoding="utf-8") as file:
    header = file.readline().strip().split(",")
    expected_columns = len(header)

# Count bad lines
bad_lines_count = 0
with open(data_path, "r", encoding="utf-8") as file:
    for i, line in enumerate(file):
        if len(line.strip().split(",")) != expected_columns:
            print(f"‚ùå Bad line at row {i+1}: {line.strip()}")
            bad_lines_count += 1

print(f"\nüîπ Total bad lines found: {bad_lines_count}")

üîπ Total bad lines found: 0

In [6]:
df = pd.read_csv(r"C:\Users\Lian4ik\Desktop\derm_project\data\merged_cleaned_dataset.csv")
print(df.info())  # Check data types and missing values
print(df.head())  # Display first few rows

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70248 entries, 0 to 70247
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   image_id    70248 non-null  object
 1   target      70248 non-null  int64
 2   sex         70248 non-null  object
 3   age_approx  70248 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 2.1+ MB
None
             image_id  target     sex  age_approx
0  ISIC_0015290_0.JPG       0  female        30.0
1  ISIC_0015291_0.JPG       0  female        35.0
2  ISIC_0015292_0.JPG       0    male        60.0
3  ISIC_0015293_0.JPG       0  female        45.0
4  ISIC_0015294_0.JPG       0  female        30.0